name: "snyk code manual test"
on: [push, pull_request]

jobs:
  build:
    name: sarif testing action
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - uses: actions/checkout@v3
      - name: Upload SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: test.json
